### PR TITLE
Create build.sh for macOS building

### PR DESCRIPTION
**Pull request by gingerbeardman**
- build script works as of 1.14.1
- requires assets folder to be copied manually from latest Windows download

### CODE REVIEW

**Comment by fallahn** [comment]
Oh! Does this mean it's working for you?

**Comment by gingerbeardman** [comment]
Yes, full screen and everything!

**Comment by fallahn** [comment]
Fantastic! When I execute the bundle I get `Codesign Error 2` (I was having a bit of a grump about it tbh 😅) - but if you have it working then there's hope yet!

**Comment by gingerbeardman** [comment]
In my script the bundle gets signed using ad-hoc signature (ie. make it OK to run locally). 

But I am still on Monterey (will be until Sonoma .2 or so) so I don't know if that still works.

[Apparency](https://mothersruin.com/software/Apparency/) says
Screen shot 2023-10-07 at 18 21 37

**Comment by fallahn** [comment]
Yup - I've been looking at your script and realised I need to sign the bundle which is in the Release directory, not the one copied to the 'bundle' directory. It works now (although I've since found a crash loading the putting course 😅). Thanks!

**Pull request merged**
